### ISSUE TITLE
[deps] Bind dependency versions

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netengine#58] opened 2021-05-27 20:34 UTC
Let's bind the dependency versions to avoid issues in the future.

I suggest also to get rid of `requirements.txt` and use `setup_requires` directly in `setup.py` which is simpler.

**Comment by purhan** [comment] 2021-05-28 03:54
This is a duplicate of https://github.com/openwisp/netengine/issues/55

**Comment by pandafy** [comment] 2021-05-28 11:43
> Let's bind the dependency versions to avoid issues in the future.
> 
> I suggest also to get rid of `requirements.txt` and use `setup_requires` directly in `setup.py` which is simpler.

**Closed by pandafy** 2021-05-28 11:43 UTC
Labels: enhancement
